import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    extend: {
      colors: {
        // Material Design 3 colors
        "surface-tint": "#004fe5",
        "on-secondary-fixed": "#2c0051",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed": "#00164f",
        "secondary": "#8126d1",
        "outline": "#737688",
        "error": "#ba1a1a",
        "secondary-container": "#9b47ec",
        "tertiary": "#9a2f00",
        "tertiary-fixed-dim": "#ffb59d",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#390c00",
        "primary": "#0047cf",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#c43e00",
        "on-tertiary-fixed-variant": "#832700",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed-variant": "#003bb0",
        "surface-bright": "#f8f9ff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "on-tertiary-container": "#ffece6",
        "on-error-container": "#93000a",
        "on-surface": "#121c2a",
        "on-background": "#121c2a",
        "inverse-primary": "#b6c4ff",
        "on-primary-container": "#eeefff",
        "surface": "#f8f9ff",
        "surface-container": "#e6eeff",
        "on-primary": "#ffffff",
        "inverse-surface": "#27313f",
        "surface-variant": "#d9e3f6",
        "on-secondary-fixed-variant": "#6800b4",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "outline-variant": "#c3c5d9",
        "primary-container": "#165dff",
        "surface-dim": "#d0dbed",
        "tertiary-fixed": "#ffdbd0",
        "secondary-fixed": "#f0dbff",
        "on-surface-variant": "#434656",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ddb8ff",
        // Deprecated but using for compatibility
        border: "#c3c5d9",
        input: "#f8f9ff",
        ring: "#0047cf",
        background: "#f8f9ff",
        foreground: "#121c2a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "40px",
        "stack-lg": "24px",
        "container-padding-mobile": "20px",
        "stack-sm": "8px",
        "gutter": "24px",
        "section-gap": "64px",
        "stack-md": "16px",
        "unit": "4px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "label-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
