/**
 * Mock data for demo mode — used when backend is unavailable
 */

export const MOCK_USERS = {
  "admin@ecosystemos.ai": {
    id: "a0000000-0000-0000-0000-000000000001",
    full_name: "Admin User",
    email: "admin@ecosystemos.ai",
    role: "admin",
    country: "Kenya",
    created_at: "2024-01-01T00:00:00Z",
  },
  "sarah@techstartup.co.ke": {
    id: "a0000000-0000-0000-0000-000000000002",
    full_name: "Sarah Kimani",
    email: "sarah@techstartup.co.ke",
    role: "startup",
    country: "Kenya",
    created_at: "2024-01-15T00:00:00Z",
  },
  "mchen@mentor.com": {
    id: "a0000000-0000-0000-0000-000000000005",
    full_name: "Dr. Michael Chen",
    email: "mchen@mentor.com",
    role: "mentor",
    country: "Singapore",
    created_at: "2024-01-10T00:00:00Z",
  },
  "james@agritech.ng": {
    id: "a0000000-0000-0000-0000-000000000003",
    full_name: "James Okonkwo",
    email: "james@agritech.ng",
    role: "startup",
    country: "Nigeria",
    created_at: "2024-02-01T00:00:00Z",
  },
};

export const MOCK_STARTUPS = [
  {
    id: "b0000000-0000-0000-0000-000000000001",
    user_id: "a0000000-0000-0000-0000-000000000002",
    startup_name: "PayFlow Africa",
    description: "AI-powered cross-border payment infrastructure for African SMEs. We reduce transaction costs by 60% using ML-based FX optimization.",
    industry: "FinTech",
    stage: "seed",
    country: "Kenya",
    website: "https://payflow.africa",
    team_size: 8,
    founded_year: 2022,
    problem_statement: "High transaction costs and slow cross-border payments in Africa cost SMEs $5B annually.",
    solution: "ML-based FX optimization with mobile-first payment rails that settle in under 30 seconds.",
    traction: "12,000 active users, $2M monthly transaction volume, 3 bank partnerships",
    funding_raised: 500000,
    funding_needed: 2000000,
    verification_score: 87.5,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "PayFlow Africa demonstrates strong fundamentals with proven traction and a clear market opportunity. The team has relevant fintech experience and the product addresses a real pain point in African cross-border payments.",
    tags: ["fintech", "payments", "africa", "ai"],
    founder_name: "Sarah Kimani",
    active_relationships: 3,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000002",
    user_id: "a0000000-0000-0000-0000-000000000003",
    startup_name: "FarmSense AI",
    description: "Precision agriculture platform using IoT sensors and AI crop prediction for smallholder farmers across West Africa.",
    industry: "AgriTech",
    stage: "pre-seed",
    country: "Nigeria",
    website: "https://farmsense.ng",
    team_size: 4,
    founded_year: 2023,
    problem_statement: "Smallholder farmers lack data-driven insights, leading to 40% crop losses annually.",
    solution: "IoT sensor network with AI-powered yield prediction and advisory delivered via SMS and app.",
    traction: "500 farmers onboarded, 23% average yield improvement, pilot in 3 states",
    funding_raised: 150000,
    funding_needed: 500000,
    verification_score: 72.0,
    risk_level: "medium",
    verification_status: "verified",
    ai_summary: "FarmSense AI shows promising early traction with measurable impact. The team needs to scale beyond the pilot phase and strengthen their go-to-market strategy.",
    tags: ["agritech", "iot", "ai", "nigeria"],
    founder_name: "James Okonkwo",
    active_relationships: 2,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000003",
    user_id: "a0000000-0000-0000-0000-000000000004",
    startup_name: "CreditBridge",
    description: "Alternative credit scoring for unbanked populations using mobile behavioral data.",
    industry: "FinTech",
    stage: "seed",
    country: "Senegal",
    website: "https://creditbridge.sn",
    team_size: 6,
    founded_year: 2022,
    problem_statement: "70% of West Africans lack formal credit history, blocking access to financial services.",
    solution: "Behavioral data analysis from mobile usage patterns generates credit scores in 60 seconds.",
    traction: "8,000 credit assessments, 94% repayment rate, 2 microfinance partnerships",
    funding_raised: 300000,
    funding_needed: 1500000,
    verification_score: 81.0,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "CreditBridge has strong product-market fit with impressive repayment metrics. The 94% repayment rate validates the scoring model's accuracy.",
    tags: ["fintech", "credit", "inclusion", "west-africa"],
    founder_name: "Amara Diallo",
    active_relationships: 2,
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000004",
    user_id: "a0000000-0000-0000-0000-000000000009",
    startup_name: "MediConnect",
    description: "Telemedicine platform connecting rural patients with urban specialists across Sub-Saharan Africa.",
    industry: "HealthTech",
    stage: "series-a",
    country: "Ghana",
    website: "https://mediconnect.gh",
    team_size: 15,
    founded_year: 2021,
    problem_statement: "Rural healthcare access gap leaves 600M Africans without specialist care.",
    solution: "Video consultation platform with AI triage, EHR integration, and offline capability.",
    traction: "45,000 consultations, 120 partner hospitals, 4.8/5 patient rating",
    funding_raised: 1200000,
    funding_needed: 5000000,
    verification_score: 91.0,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "MediConnect is a standout performer with exceptional traction and a proven business model. Series A readiness is high.",
    tags: ["healthtech", "telemedicine", "africa", "ai"],
    founder_name: "Kwame Mensah",
    active_relationships: 2,
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000005",
    user_id: "a0000000-0000-0000-0000-000000000010",
    startup_name: "LearnPath",
    description: "Adaptive learning platform for K-12 students in the MENA region using AI personalization.",
    industry: "EdTech",
    stage: "seed",
    country: "Egypt",
    website: "https://learnpath.eg",
    team_size: 10,
    founded_year: 2022,
    problem_statement: "One-size-fits-all education fails 60% of diverse learners in MENA.",
    solution: "AI-personalized curriculum with gamification, parent dashboards, and Arabic language support.",
    traction: "25,000 students, 4.7/5 teacher rating, 3 school district partnerships",
    funding_raised: 400000,
    funding_needed: 2000000,
    verification_score: 78.5,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "LearnPath shows strong product adoption with excellent teacher satisfaction scores. The MENA EdTech market is underserved and growing rapidly.",
    tags: ["edtech", "ai", "mena", "k12"],
    founder_name: "Fatima Al-Hassan",
    active_relationships: 1,
    created_at: "2024-02-10T00:00:00Z",
  },
];

export const MOCK_MENTORS = [
  {
    id: "c0000000-0000-0000-0000-000000000001",
    user_id: "a0000000-0000-0000-0000-000000000005",
    full_name: "Dr. Michael Chen",
    email: "mchen@mentor.com",
    bio: "Former CTO at 3 successful fintech startups. Expert in scaling payment systems across Asia and Africa. 2 exits, $180M total raised.",
    expertise: ["fintech", "payments", "scaling", "product-strategy", "fundraising"],
    industries: ["FinTech", "Banking", "Payments"],
    years_experience: 18,
    availability: "available",
    mentorship_style: "Hands-on, weekly sessions with milestone tracking",
    max_startups: 3,
    current_startups: 1,
    rating: 4.9,
    total_reviews: 47,
    company: "PayScale Ventures",
    title: "Managing Partner",
    location: "Singapore",
    timezone: "SGT",
    languages: ["English", "Mandarin"],
    active_mentorships: 1,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "c0000000-0000-0000-0000-000000000002",
    user_id: "a0000000-0000-0000-0000-000000000006",
    full_name: "Priya Sharma",
    email: "priya@mentor.in",
    bio: "Serial entrepreneur with 2 exits. Deep expertise in B2B SaaS and enterprise sales in emerging markets. Former VP at Sequoia-backed startup.",
    expertise: ["saas", "enterprise-sales", "product-market-fit", "go-to-market", "fundraising"],
    industries: ["SaaS", "Enterprise", "B2B"],
    years_experience: 14,
    availability: "available",
    mentorship_style: "Strategic advisor, bi-weekly sessions",
    max_startups: 4,
    current_startups: 2,
    rating: 4.7,
    total_reviews: 32,
    company: "Emerge Capital",
    title: "Venture Partner",
    location: "Mumbai",
    timezone: "IST",
    languages: ["English", "Hindi"],
    active_mentorships: 2,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "c0000000-0000-0000-0000-000000000003",
    user_id: "a0000000-0000-0000-0000-000000000007",
    full_name: "David Osei",
    email: "david@mentor.gh",
    bio: "AgriTech pioneer with 20 years in precision agriculture. Built and sold 2 agri-data companies. Deep network across African agricultural ministries.",
    expertise: ["agritech", "iot", "data-analytics", "supply-chain", "impact-investing"],
    industries: ["AgriTech", "FoodTech", "CleanTech"],
    years_experience: 20,
    availability: "limited",
    mentorship_style: "Monthly deep-dives with network introductions",
    max_startups: 2,
    current_startups: 1,
    rating: 4.8,
    total_reviews: 28,
    company: "AgroVentures Africa",
    title: "Founder & CEO",
    location: "Accra",
    timezone: "GMT",
    languages: ["English", "Twi"],
    active_mentorships: 1,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_INVESTORS = [
  {
    id: "d0000000-0000-0000-0000-000000000001",
    user_id: "a0000000-0000-0000-0000-000000000008",
    full_name: "Victoria Fund",
    firm_name: "Horizon Africa Fund",
    investment_thesis: "Backing Africa-focused tech startups solving real problems at scale with strong founding teams.",
    focus_industries: ["FinTech", "HealthTech", "AgriTech", "EdTech"],
    investment_stages: ["seed", "series-a"],
    ticket_size_min: 250000,
    ticket_size_max: 2000000,
    portfolio_size: 23,
    country: "USA",
    website: "https://horizonafrica.vc",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_PROGRAMMES = [
  {
    id: "e0000000-0000-0000-0000-000000000001",
    programme_name: "Africa Innovation Accelerator",
    description: "Pan-African accelerator for early-stage tech startups with $100K equity-free grant and 16-week intensive programme.",
    organizer: "African Development Bank",
    country: "Pan-Africa",
    focus_area: ["FinTech", "AgriTech", "HealthTech", "CleanTech"],
    cohort_size: 20,
    duration_weeks: 16,
    funding_offered: 100000,
    equity_taken: 0,
    status: "open",
    benefits: ["$100K grant", "Mentorship", "Network access", "Demo Day", "Investor introductions"],
    enrolled_startups: 12,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "e0000000-0000-0000-0000-000000000002",
    programme_name: "GovTech Sandbox Kenya",
    description: "Government-backed programme for civic tech and digital public services innovation.",
    organizer: "Kenya ICT Authority",
    country: "Kenya",
    focus_area: ["GovTech", "FinTech", "HealthTech"],
    cohort_size: 15,
    duration_weeks: 12,
    funding_offered: 50000,
    equity_taken: 0,
    status: "open",
    benefits: ["$50K grant", "Government contracts", "Regulatory sandbox", "Technical support"],
    enrolled_startups: 8,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "e0000000-0000-0000-0000-000000000003",
    programme_name: "West Africa FinTech Hub",
    description: "Regional fintech accelerator focused on financial inclusion across ECOWAS member states.",
    organizer: "ECOWAS Innovation Fund",
    country: "Nigeria",
    focus_area: ["FinTech", "InsurTech", "WealthTech"],
    cohort_size: 12,
    duration_weeks: 20,
    funding_offered: 150000,
    equity_taken: 5,
    status: "ongoing",
    benefits: ["$150K investment", "Banking partnerships", "Regulatory guidance", "Regional expansion support"],
    enrolled_startups: 10,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_RELATIONSHIPS = [
  {
    id: "f0000000-0000-0000-0000-000000000001",
    relationship_type: "mentor_startup",
    startup_id: "b0000000-0000-0000-0000-000000000001",
    mentor_id: "c0000000-0000-0000-0000-000000000001",
    match_score: 94.5,
    confidence_score: 91.0,
    engagement_health: "excellent",
    status: "active",
    ai_generated: true,
    ai_reasoning: "Strong alignment: both in fintech payments space, mentor has direct experience scaling similar products in African markets.",
    startup_name: "PayFlow Africa",
    mentor_name: "Dr. Michael Chen",
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000002",
    relationship_type: "mentor_startup",
    startup_id: "b0000000-0000-0000-0000-000000000002",
    mentor_id: "c0000000-0000-0000-0000-000000000003",
    match_score: 88.0,
    confidence_score: 85.5,
    engagement_health: "good",
    status: "active",
    ai_generated: true,
    ai_reasoning: "Excellent match: mentor is AgriTech pioneer with IoT expertise, directly relevant to FarmSense AI product.",
    startup_name: "FarmSense AI",
    mentor_name: "David Osei",
    created_at: "2024-02-05T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000003",
    relationship_type: "startup_programme",
    startup_id: "b0000000-0000-0000-0000-000000000001",
    programme_id: "e0000000-0000-0000-0000-000000000001",
    match_score: 89.0,
    confidence_score: 87.0,
    engagement_health: "good",
    status: "active",
    ai_generated: true,
    ai_reasoning: "PayFlow Africa aligns with programme focus on FinTech and financial inclusion across Africa.",
    startup_name: "PayFlow Africa",
    programme_name: "Africa Innovation Accelerator",
    created_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000004",
    relationship_type: "startup_investor",
    startup_id: "b0000000-0000-0000-0000-000000000004",
    investor_id: "d0000000-0000-0000-0000-000000000001",
    match_score: 92.0,
    confidence_score: 89.5,
    engagement_health: "excellent",
    status: "active",
    ai_generated: true,
    ai_reasoning: "MediConnect is in HealthTech at Series A stage, perfectly matching Horizon Africa Fund investment thesis.",
    startup_name: "MediConnect",
    investor_name: "Horizon Africa Fund",
    created_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000005",
    relationship_type: "startup_programme",
    startup_id: "b0000000-0000-0000-0000-000000000003",
    programme_id: "e0000000-0000-0000-0000-000000000003",
    match_score: 95.0,
    confidence_score: 93.0,
    engagement_health: "excellent",
    status: "active",
    ai_generated: true,
    ai_reasoning: "CreditBridge is a perfect fit for West Africa FinTech Hub — financial inclusion focus and West African market.",
    startup_name: "CreditBridge",
    programme_name: "West Africa FinTech Hub",
    created_at: "2024-02-20T00:00:00Z",
  },
];

export const MOCK_DASHBOARD = {
  stats: {
    startups: { total: "5", verified: "5", avg_score: "82.0", low_risk: "4", high_risk: "0" },
    mentors: { total: "3", available: "2", avg_rating: "4.8" },
    programmes: { total: "3", open: "2", ongoing: "1" },
    relationships: { total: "5", active: "5", ai_generated: "5", avg_match_score: "91.7", excellent_health: "3" },
  },
  recent: {
    startups: MOCK_STARTUPS.slice(0, 5),
    relationships: MOCK_RELATIONSHIPS.slice(0, 5),
  },
  distributions: {
    industry: [
      { industry: "FinTech", count: "2" },
      { industry: "AgriTech", count: "1" },
      { industry: "HealthTech", count: "1" },
      { industry: "EdTech", count: "1" },
    ],
    verification: [
      { verification_status: "verified", count: "5" },
      { verification_status: "pending", count: "0" },
    ],
  },
  insights: {
    ecosystem_health_score: 78,
    headline: "EcosystemOS is accelerating — 5 AI-matched relationships driving strong engagement across FinTech and HealthTech sectors.",
    growth_trajectory: "accelerating",
    key_insights: [
      "FinTech sector leads with 2 high-scoring startups and 94.5% avg match quality",
      "All 5 relationships are AI-generated with avg match score of 91.7%",
      "MediConnect at Series A is the ecosystem's highest-value startup (score: 91)",
      "Mentor capacity is near optimal — 2 of 3 mentors actively engaged",
    ],
    opportunities: [
      "Cross-sector collaboration between PayFlow Africa and MediConnect for health payments",
      "West Africa expansion opportunity — CreditBridge + West Africa FinTech Hub alignment is 95%",
      "LearnPath and FarmSense AI are strong candidates for Africa Innovation Accelerator",
    ],
    risks: [
      "Mentor bandwidth may constrain ecosystem growth — recruit 2-3 more mentors",
      "Geographic concentration in East Africa — expand West and North Africa pipeline",
    ],
    recommendations: [
      "Recruit 3 additional mentors in HealthTech and EdTech verticals",
      "Launch investor matching for FarmSense AI and LearnPath at seed stage",
      "Activate relationship health monitoring for all 5 active relationships",
    ],
  },
};

export const MOCK_GRAPH = {
  nodes: [
    ...MOCK_STARTUPS.map((s, i) => ({
      id: s.id, type: "startup",
      data: { label: s.startup_name, industry: s.industry, stage: s.stage, verification_score: s.verification_score, type: "startup" },
      position: { x: 80 + (i % 3) * 220, y: 300 + Math.floor(i / 3) * 160 },
    })),
    ...MOCK_MENTORS.map((m, i) => ({
      id: m.id, type: "mentor",
      data: { label: m.full_name, rating: m.rating, availability: m.availability, type: "mentor" },
      position: { x: 700, y: 80 + i * 160 },
    })),
    ...MOCK_PROGRAMMES.map((p, i) => ({
      id: p.id, type: "programme",
      data: { label: p.programme_name, status: p.status, type: "programme" },
      position: { x: 980, y: 80 + i * 160 },
    })),
    ...MOCK_INVESTORS.map((inv, i) => ({
      id: inv.id, type: "investor",
      data: { label: inv.firm_name, type: "investor" },
      position: { x: 400, y: 50 + i * 120 },
    })),
  ],
  edges: MOCK_RELATIONSHIPS.map((r) => ({
    id: r.id,
    source: r.startup_id || r.mentor_id || "",
    target: r.mentor_id || r.programme_id || r.investor_id || "",
    type: r.relationship_type,
    animated: r.engagement_health === "excellent",
    data: { match_score: r.match_score, engagement_health: r.engagement_health, status: r.status, ai_generated: r.ai_generated },
    label: `${Math.round(r.match_score)}%`,
  })),
};

export const MOCK_MENTOR_MATCHES = [
  {
    mentor_id: "c0000000-0000-0000-0000-000000000001",
    mentor_name: "Dr. Michael Chen",
    mentor_title: "Managing Partner",
    mentor_company: "PayScale Ventures",
    mentor_location: "Singapore",
    mentor_expertise: ["fintech", "payments", "scaling", "fundraising"],
    mentor_industries: ["FinTech", "Banking"],
    mentor_rating: 4.9,
    mentor_availability: "available",
    years_experience: 18,
    compatibility_score: 94.5,
    confidence_score: 91.0,
    mentorship_quality: "excellent",
    expertise_relevance: 0.95,
    reasoning: "Dr. Chen has directly scaled fintech payment products in African markets — his experience is a near-perfect match for PayFlow Africa's growth stage and challenges.",
    recommended_focus_areas: ["Go-to-market strategy", "Fundraising preparation", "Banking partnerships"],
    estimated_impact: "High — can accelerate Series A readiness by 6-9 months",
  },
  {
    mentor_id: "c0000000-0000-0000-0000-000000000002",
    mentor_name: "Priya Sharma",
    mentor_title: "Venture Partner",
    mentor_company: "Emerge Capital",
    mentor_location: "Mumbai",
    mentor_expertise: ["saas", "enterprise-sales", "go-to-market", "fundraising"],
    mentor_industries: ["SaaS", "Enterprise"],
    mentor_rating: 4.7,
    mentor_availability: "available",
    years_experience: 14,
    compatibility_score: 78.0,
    confidence_score: 74.0,
    mentorship_quality: "high",
    expertise_relevance: 0.72,
    reasoning: "Priya's enterprise sales expertise is valuable for PayFlow Africa's B2B SME acquisition strategy, though her fintech depth is less direct than Dr. Chen.",
    recommended_focus_areas: ["Enterprise sales", "Investor relations", "Team building"],
    estimated_impact: "Medium — strong support for B2B growth strategy",
  },
];

export const MOCK_PROGRAMME_MATCHES = [
  {
    programme_id: "e0000000-0000-0000-0000-000000000001",
    programme_name: "Africa Innovation Accelerator",
    organizer: "African Development Bank",
    country: "Pan-Africa",
    focus_area: ["FinTech", "AgriTech", "HealthTech"],
    duration_weeks: 16,
    funding_offered: 100000,
    status: "open",
    benefits: ["$100K grant", "Mentorship", "Demo Day", "Investor introductions"],
    fit_score: 89.0,
    confidence_score: 87.0,
    eligibility_assessment: "eligible",
    reasoning: "Strong alignment with programme's FinTech focus. PayFlow Africa's traction and team quality meet the eligibility bar comfortably.",
    application_recommendation: "strong_apply",
  },
  {
    programme_id: "e0000000-0000-0000-0000-000000000002",
    programme_name: "GovTech Sandbox Kenya",
    organizer: "Kenya ICT Authority",
    country: "Kenya",
    focus_area: ["GovTech", "FinTech"],
    duration_weeks: 12,
    funding_offered: 50000,
    status: "open",
    benefits: ["$50K grant", "Government contracts", "Regulatory sandbox"],
    fit_score: 76.0,
    confidence_score: 72.0,
    eligibility_assessment: "likely_eligible",
    reasoning: "Kenya-based startup with FinTech focus aligns well. The regulatory sandbox access could accelerate licensing.",
    application_recommendation: "apply",
  },
];

export const MOCK_VERIFICATION = {
  verification_score: 87.5,
  risk_level: "low",
  industry_classification: "FinTech",
  stage_classification: "seed",
  legitimacy_score: 85,
  confidence_level: 0.88,
  risk_factors: [
    "Competitive market with established players (M-Pesa, Flutterwave)",
    "Regulatory complexity across multiple African jurisdictions",
  ],
  strengths: [
    "Strong traction with 12,000 active users and $2M monthly volume",
    "Experienced team with relevant fintech background",
    "Clear revenue model with proven unit economics",
    "Strategic bank partnerships de-risk the business",
  ],
  recommendations: [
    "Accelerate Series A fundraising — metrics support a $3-5M round",
    "Expand to 2 additional African markets in next 12 months",
    "Strengthen compliance team ahead of regulatory expansion",
  ],
  ai_summary: "PayFlow Africa demonstrates strong fundamentals with proven traction and a clear market opportunity. The team has relevant fintech experience and the product addresses a real pain point. Series A readiness is high.",
};

export const MOCK_ANALYTICS = {
  monthly_growth: [
    { month: "2024-01-01", startups_added: 2 },
    { month: "2024-02-01", startups_added: 3 },
    { month: "2024-03-01", startups_added: 1 },
  ],
  top_startups: MOCK_STARTUPS.sort((a, b) => b.verification_score - a.verification_score).slice(0, 5),
  engagement_trend: [
    { week: "2024-01-01", engagements: 3 },
    { week: "2024-01-08", engagements: 5 },
    { week: "2024-01-15", engagements: 4 },
    { week: "2024-01-22", engagements: 7 },
  ],
};
