/**
 * Mock data for demo mode — used when backend is unavailable
 */

export const MOCK_USERS = {
  "admin@ecosystemos.ai": {
    id: "a0000000-0000-0000-0000-000000000001",
    full_name: "Admin User",
    email: "admin@ecosystemos.ai",
    role: "admin",
    country: "Kenya",
    created_at: "2024-01-01T00:00:00Z",
  },
  "sarah@techstartup.co.ke": {
    id: "a0000000-0000-0000-0000-000000000002",
    full_name: "Sarah Kimani",
    email: "sarah@techstartup.co.ke",
    role: "startup",
    country: "Kenya",
    created_at: "2024-01-15T00:00:00Z",
  },
  "mchen@mentor.com": {
    id: "a0000000-0000-0000-0000-000000000005",
    full_name: "Dr. Michael Chen",
    email: "mchen@mentor.com",
    role: "mentor",
    country: "Singapore",
    created_at: "2024-01-10T00:00:00Z",
  },
  "james@agritech.ng": {
    id: "a0000000-0000-0000-0000-000000000003",
    full_name: "James Okonkwo",
    email: "james@agritech.ng",
    role: "startup",
    country: "Nigeria",
    created_at: "2024-02-01T00:00:00Z",
  },
};

export const MOCK_STARTUPS = [
  {
    id: "b0000000-0000-0000-0000-000000000001",
    user_id: "a0000000-0000-0000-0000-000000000002",
    startup_name: "PayFlow Africa",
    description: "AI-powered cross-border payment infrastructure for African SMEs. We reduce transaction costs by 60% using ML-based FX optimization.",
    industry: "FinTech",
    stage: "seed",
    country: "Kenya",
    website: "https://payflow.africa",
    team_size: 8,
    founded_year: 2022,
    problem_statement: "High transaction costs and slow cross-border payments in Africa cost SMEs $5B annually.",
    solution: "ML-based FX optimization with mobile-first payment rails that settle in under 30 seconds.",
    traction: "12,000 active users, $2M monthly transaction volume, 3 bank partnerships",
    funding_raised: 500000,
    funding_needed: 2000000,
    verification_score: 87.5,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "PayFlow Africa demonstrates strong fundamentals with proven traction and a clear market opportunity. The team has relevant fintech experience and the product addresses a real pain point in African cross-border payments.",
    tags: ["fintech", "payments", "africa", "ai"],
    founder_name: "Sarah Kimani",
    active_relationships: 3,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000002",
    user_id: "a0000000-0000-0000-0000-000000000003",
    startup_name: "FarmSense AI",
    description: "Precision agriculture platform using IoT sensors and AI crop prediction for smallholder farmers across West Africa.",
    industry: "AgriTech",
    stage: "pre-seed",
    country: "Nigeria",
    website: "https://farmsense.ng",
    team_size: 4,
    founded_year: 2023,
    problem_statement: "Smallholder farmers lack data-driven insights, leading to 40% crop losses annually.",
    solution: "IoT sensor network with AI-powered yield prediction and advisory delivered via SMS and app.",
    traction: "500 farmers onboarded, 23% average yield improvement, pilot in 3 states",
    funding_raised: 150000,
    funding_needed: 500000,
    verification_score: 72.0,
    risk_level: "medium",
    verification_status: "verified",
    ai_summary: "FarmSense AI shows promising early traction with measurable impact. The team needs to scale beyond the pilot phase and strengthen their go-to-market strategy.",
    tags: ["agritech", "iot", "ai", "nigeria"],
    founder_name: "James Okonkwo",
    active_relationships: 2,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000003",
    user_id: "a0000000-0000-0000-0000-000000000004",
    startup_name: "CreditBridge",
    description: "Alternative credit scoring for unbanked populations using mobile behavioral data.",
    industry: "FinTech",
    stage: "seed",
    country: "Senegal",
    website: "https://creditbridge.sn",
    team_size: 6,
    founded_year: 2022,
    problem_statement: "70% of West Africans lack formal credit history, blocking access to financial services.",
    solution: "Behavioral data analysis from mobile usage patterns generates credit scores in 60 seconds.",
    traction: "8,000 credit assessments, 94% repayment rate, 2 microfinance partnerships",
    funding_raised: 300000,
    funding_needed: 1500000,
    verification_score: 81.0,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "CreditBridge has strong product-market fit with impressive repayment metrics. The 94% repayment rate validates the scoring model's accuracy.",
    tags: ["fintech", "credit", "inclusion", "west-africa"],
    founder_name: "Amara Diallo",
    active_relationships: 2,
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000004",
    user_id: "a0000000-0000-0000-0000-000000000009",
    startup_name: "MediConnect",
    description: "Telemedicine platform connecting rural patients with urban specialists across Sub-Saharan Africa.",
    industry: "HealthTech",
    stage: "series-a",
    country: "Ghana",
    website: "https://mediconnect.gh",
    team_size: 15,
    founded_year: 2021,
    problem_statement: "Rural healthcare access gap leaves 600M Africans without specialist care.",
    solution: "Video consultation platform with AI triage, EHR integration, and offline capability.",
    traction: "45,000 consultations, 120 partner hospitals, 4.8/5 patient rating",
    funding_raised: 1200000,
    funding_needed: 5000000,
    verification_score: 91.0,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "MediConnect is a standout performer with exceptional traction and a proven business model. Series A readiness is high.",
    tags: ["healthtech", "telemedicine", "africa", "ai"],
    founder_name: "Kwame Mensah",
    active_relationships: 2,
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "b0000000-0000-0000-0000-000000000005",
    user_id: "a0000000-0000-0000-0000-000000000010",
    startup_name: "LearnPath",
    description: "Adaptive learning platform for K-12 students in the MENA region using AI personalization.",
    industry: "EdTech",
    stage: "seed",
    country: "Egypt",
    website: "https://learnpath.eg",
    team_size: 10,
    founded_year: 2022,
    problem_statement: "One-size-fits-all education fails 60% of diverse learners in MENA.",
    solution: "AI-personalized curriculum with gamification, parent dashboards, and Arabic language support.",
    traction: "25,000 students, 4.7/5 teacher rating, 3 school district partnerships",
    funding_raised: 400000,
    funding_needed: 2000000,
    verification_score: 78.5,
    risk_level: "low",
    verification_status: "verified",
    ai_summary: "LearnPath shows strong product adoption with excellent teacher satisfaction scores. The MENA EdTech market is underserved and growing rapidly.",
    tags: ["edtech", "ai", "mena", "k12"],
    founder_name: "Fatima Al-Hassan",
    active_relationships: 1,
    created_at: "2024-02-10T00:00:00Z",
  },
];

export const MOCK_MENTORS = [
  {
    id: "c0000000-0000-0000-0000-000000000001",
    user_id: "a0000000-0000-0000-0000-000000000005",
    full_name: "Dr. Michael Chen",
    email: "mchen@mentor.com",
    bio: "Former CTO at 3 successful fintech startups. Expert in scaling payment systems across Asia and Africa. 2 exits, $180M total raised.",
    expertise: ["fintech", "payments", "scaling", "product-strategy", "fundraising"],
    industries: ["FinTech", "Banking", "Payments"],
    years_experience: 18,
    availability: "available",
    mentorship_style: "Hands-on, weekly sessions with milestone tracking",
    max_startups: 3,
    current_startups: 1,
    rating: 4.9,
    total_reviews: 47,
    company: "PayScale Ventures",
    title: "Managing Partner",
    location: "Singapore",
    timezone: "SGT",
    languages: ["English", "Mandarin"],
    active_mentorships: 1,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "c0000000-0000-0000-0000-000000000002",
    user_id: "a0000000-0000-0000-0000-000000000006",
    full_name: "Priya Sharma",
    email: "priya@mentor.in",
    bio: "Serial entrepreneur with 2 exits. Deep expertise in B2B SaaS and enterprise sales in emerging markets. Former VP at Sequoia-backed startup.",
    expertise: ["saas", "enterprise-sales", "product-market-fit", "go-to-market", "fundraising"],
    industries: ["SaaS", "Enterprise", "B2B"],
    years_experience: 14,
    availability: "available",
    mentorship_style: "Strategic advisor, bi-weekly sessions",
    max_startups: 4,
    current_startups: 2,
    rating: 4.7,
    total_reviews: 32,
    company: "Emerge Capital",
    title: "Venture Partner",
    location: "Mumbai",
    timezone: "IST",
    languages: ["English", "Hindi"],
    active_mentorships: 2,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "c0000000-0000-0000-0000-000000000003",
    user_id: "a0000000-0000-0000-0000-000000000007",
    full_name: "David Osei",
    email: "david@mentor.gh",
    bio: "AgriTech pioneer with 20 years in precision agriculture. Built and sold 2 agri-data companies. Deep network across African agricultural ministries.",
    expertise: ["agritech", "iot", "data-analytics", "supply-chain", "impact-investing"],
    industries: ["AgriTech", "FoodTech", "CleanTech"],
    years_experience: 20,
    availability: "limited",
    mentorship_style: "Monthly deep-dives with network introductions",
    max_startups: 2,
    current_startups: 1,
    rating: 4.8,
    total_reviews: 28,
    company: "AgroVentures Africa",
    title: "Founder & CEO",
    location: "Accra",
    timezone: "GMT",
    languages: ["English", "Twi"],
    active_mentorships: 1,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_INVESTORS = [
  {
    id: "d0000000-0000-0000-0000-000000000001",
    user_id: "a0000000-0000-0000-0000-000000000008",
    full_name: "Victoria Fund",
    firm_name: "Horizon Africa Fund",
    investment_thesis: "Backing Africa-focused tech startups solving real problems at scale with strong founding teams.",
    focus_industries: ["FinTech", "HealthTech", "AgriTech", "EdTech"],
    investment_stages: ["seed", "series-a"],
    ticket_size_min: 250000,
    ticket_size_max: 2000000,
    portfolio_size: 23,
    country: "USA",
    website: "https://horizonafrica.vc",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_PROGRAMMES = [
  {
    id: "e0000000-0000-0000-0000-000000000001",
    programme_name: "Africa Innovation Accelerator",
    description: "Pan-African accelerator for early-stage tech startups with $100K equity-free grant and 16-week intensive programme.",
    organizer: "African Development Bank",
    country: "Pan-Africa",
    focus_area: ["FinTech", "AgriTech", "HealthTech", "CleanTech"],
    cohort_size: 20,
    duration_weeks: 16,
    funding_offered: 100000,
    equity_taken: 0,
    status: "open",
    benefits: ["$100K grant", "Mentorship", "Network access", "Demo Day", "Investor introductions"],
    enrolled_startups: 12,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "e0000000-0000-0000-0000-000000000002",
    programme_name: "GovTech Sandbox Kenya",
    description: "Government-backed programme for civic tech and digital public services innovation.",
    organizer: "Kenya ICT Authority",
    country: "Kenya",
    focus_area: ["GovTech", "FinTech", "HealthTech"],
    cohort_size: 15,
    duration_weeks: 12,
    funding_offered: 50000,
    equity_taken: 0,
    status: "open",
    benefits: ["$50K grant", "Government contracts", "Regulatory sandbox", "Technical support"],
    enrolled_startups: 8,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "e0000000-0000-0000-0000-000000000003",
    programme_name: "West Africa FinTech Hub",
    description: "Regional fintech accelerator focused on financial inclusion across ECOWAS member states.",
    organizer: "ECOWAS Innovation Fund",
    country: "Nigeria",
    focus_area: ["FinTech", "InsurTech", "WealthTech"],
    cohort_size: 12,
    duration_weeks: 20,
    funding_offered: 150000,
    equity_taken: 5,
    status: "ongoing",
    benefits: ["$150K investment", "Banking partnerships", "Regulatory guidance", "Regional expansion support"],
    enrolled_startups: 10,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_RELATIONSHIPS = [
  {
    id: "f0000000-0000-0000-0000-000000000001",
    relationship_type: "mentor_startup",
    startup_id: "b0000000-0000-0000-0000-000000000001",
    mentor_id: "c0000000-0000-0000-0000-000000000001",
    match_score: 94.5,
    confidence_score: 91.0,
    engagement_health: "excellent",
    status: "active",
    ai_generated: true,
    ai_reasoning: "Strong alignment: both in fintech payments space, mentor has direct experience scaling similar products in African markets.",
    startup_name: "PayFlow Africa",
    mentor_name: "Dr. Michael Chen",
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000002",
    relationship_type: "mentor_startup",
    startup_id: "b0000000-0000-0000-0000-000000000002",
    mentor_id: "c0000000-0000-0000-0000-000000000003",
    match_score: 88.0,
    confidence_score: 85.5,
    engagement_health: "good",
    status: "active",
    ai_generated: true,
    ai_reasoning: "Excellent match: mentor is AgriTech pioneer with IoT expertise, directly relevant to FarmSense AI product.",
    startup_name: "FarmSense AI",
    mentor_name: "David Osei",
    created_at: "2024-02-05T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000003",
    relationship_type: "startup_programme",
    startup_id: "b0000000-0000-0000-0000-000000000001",
    programme_id: "e0000000-0000-0000-0000-000000000001",
    match_score: 89.0,
    confidence_score: 87.0,
    engagement_health: "good",
    status: "active",
    ai_generated: true,
    ai_reasoning: "PayFlow Africa aligns with programme focus on FinTech and financial inclusion across Africa.",
    startup_name: "PayFlow Africa",
    programme_name: "Africa Innovation Accelerator",
    created_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000004",
    relationship_type: "startup_investor",
    startup_id: "b0000000-0000-0000-0000-000000000004",
    investor_id: "d0000000-0000-0000-0000-000000000001",
    match_score: 92.0,
    confidence_score: 89.5,
    engagement_health: "excellent",
    status: "active",
    ai_generated: true,
    ai_reasoning: "MediConnect is in HealthTech at Series A stage, perfectly matching Horizon Africa Fund investment thesis.",
    startup_name: "MediConnect",
    investor_name: "Horizon Africa Fund",
    created_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "f0000000-0000-0000-0000-000000000005",
    relationship_type: "startup_programme",
    startup_id: "b0000000-0000-0000-0000-000000000003",
    programme_id: "e0000000-0000-0000-0000-000000000003",
    match_score: 95.0,
    confidence_score: 93.0,
    engagement_health: "excellent",
    status: "active",
    ai_generated: true,
    ai_reasoning: "CreditBridge is a perfect fit for West Africa FinTech Hub — financial inclusion focus and West African market.",
    startup_name: "CreditBridge",
    programme_name: "West Africa FinTech Hub",
    created_at: "2024-02-20T00:00:00Z",
  },
];

export const MOCK_DASHBOARD = {
  stats: {
    startups: { total: "5", verified: "5", avg_score: "82.0", low_risk: "4", high_risk: "0" },
    mentors: { total: "3", available: "2", avg_rating: "4.8" },
    programmes: { total: "3", open: "2", ongoing: "1" },
    relationships: { total: "5", active: "5", ai_generated: "5", avg_match_score: "91.7", excellent_health: "3" },
  },
  recent: {
    startups: MOCK_STARTUPS.slice(0, 5),
    relationships: MOCK_RELATIONSHIPS.slice(0, 5),
  },
  distributions: {
    industry: [
      { industry: "FinTech", count: "2" },
      { industry: "AgriTech", count: "1" },
      { industry: "HealthTech", count: "1" },
      { industry: "EdTech", count: "1" },
    ],
    verification: [
      { verification_status: "verified", count: "5" },
      { verification_status: "pending", count: "0" },
    ],
  },
  insights: {
    ecosystem_health_score: 78,
    headline: "EcosystemOS is accelerating — 5 AI-matched relationships driving strong engagement across FinTech and HealthTech sectors.",
    growth_trajectory: "accelerating",
    key_insights: [
      "FinTech sector leads with 2 high-scoring startups and 94.5% avg match quality",
      "All 5 relationships are AI-generated with avg match score of 91.7%",
      "MediConnect at Series A is the ecosystem's highest-value startup (score: 91)",
      "Mentor capacity is near optimal — 2 of 3 mentors actively engaged",
    ],
    opportunities: [
      "Cross-sector collaboration between PayFlow Africa and MediConnect for health payments",
      "West Africa expansion opportunity — CreditBridge + West Africa FinTech Hub alignment is 95%",
      "LearnPath and FarmSense AI are strong candidates for Africa Innovation Accelerator",
    ],
    risks: [
      "Mentor bandwidth may constrain ecosystem growth — recruit 2-3 more mentors",
      "Geographic concentration in East Africa — expand West and North Africa pipeline",
    ],
    recommendations: [
      "Recruit 3 additional mentors in HealthTech and EdTech verticals",
      "Launch investor matching for FarmSense AI and LearnPath at seed stage",
      "Activate relationship health monitoring for all 5 active relationships",
    ],
  },
};

export const MOCK_GRAPH = {
  nodes: [
    ...MOCK_STARTUPS.map((s, i) => ({
      id: s.id, type: "startup",
      data: { label: s.startup_name, industry: s.industry, stage: s.stage, verification_score: s.verification_score, type: "startup" },
      position: { x: 80 + (i % 3) * 220, y: 300 + Math.floor(i / 3) * 160 },
    })),
    ...MOCK_MENTORS.map((m, i) => ({
      id: m.id, type: "mentor",
      data: { label: m.full_name, rating: m.rating, availability: m.availability, type: "mentor" },
      position: { x: 700, y: 80 + i * 160 },
    })),
    ...MOCK_PROGRAMMES.map((p, i) => ({
      id: p.id, type: "programme",
      data: { label: p.programme_name, status: p.status, type: "programme" },
      position: { x: 980, y: 80 + i * 160 },
    })),
    ...MOCK_INVESTORS.map((inv, i) => ({
      id: inv.id, type: "investor",
      data: { label: inv.firm_name, type: "investor" },
      position: { x: 400, y: 50 + i * 120 },
    })),
  ],
  edges: MOCK_RELATIONSHIPS.map((r) => ({
    id: r.id,
    source: r.startup_id || r.mentor_id || "",
    target: r.mentor_id || r.programme_id || r.investor_id || "",
    type: r.relationship_type,
    animated: r.engagement_health === "excellent",
    data: { match_score: r.match_score, engagement_health: r.engagement_health, status: r.status, ai_generated: r.ai_generated },
    label: `${Math.round(r.match_score)}%`,
  })),
};

export const MOCK_MENTOR_MATCHES = [
  {
    mentor_id: "c0000000-0000-0000-0000-000000000001",
    mentor_name: "Dr. Michael Chen",
    mentor_title: "Managing Partner",
    mentor_company: "PayScale Ventures",
    mentor_location: "Singapore",
    mentor_expertise: ["fintech", "payments", "scaling", "fundraising"],
    mentor_industries: ["FinTech", "Banking"],
    mentor_rating: 4.9,
    mentor_availability: "available",
    years_experience: 18,
    compatibility_score: 94.5,
    confidence_score: 91.0,
    mentorship_quality: "excellent",
    expertise_relevance: 0.95,
    reasoning: "Dr. Chen has directly scaled fintech payment products in African markets — his experience is a near-perfect match for PayFlow Africa's growth stage and challenges.",
    recommended_focus_areas: ["Go-to-market strategy", "Fundraising preparation", "Banking partnerships"],
    estimated_impact: "High — can accelerate Series A readiness by 6-9 months",
  },
  {
    mentor_id: "c0000000-0000-0000-0000-000000000002",
    mentor_name: "Priya Sharma",
    mentor_title: "Venture Partner",
    mentor_company: "Emerge Capital",
    mentor_location: "Mumbai",
    mentor_expertise: ["saas", "enterprise-sales", "go-to-market", "fundraising"],
    mentor_industries: ["SaaS", "Enterprise"],
    mentor_rating: 4.7,
    mentor_availability: "available",
    years_experience: 14,
    compatibility_score: 78.0,
    confidence_score: 74.0,
    mentorship_quality: "high",
    expertise_relevance: 0.72,
    reasoning: "Priya's enterprise sales expertise is valuable for PayFlow Africa's B2B SME acquisition strategy, though her fintech depth is less direct than Dr. Chen.",
    recommended_focus_areas: ["Enterprise sales", "Investor relations", "Team building"],
    estimated_impact: "Medium — strong support for B2B growth strategy",
  },
];

export const MOCK_PROGRAMME_MATCHES = [
  {
    programme_id: "e0000000-0000-0000-0000-000000000001",
    programme_name: "Africa Innovation Accelerator",
    organizer: "African Development Bank",
    country: "Pan-Africa",
    focus_area: ["FinTech", "AgriTech", "HealthTech"],
    duration_weeks: 16,
    funding_offered: 100000,
    status: "open",
    benefits: ["$100K grant", "Mentorship", "Demo Day", "Investor introductions"],
    fit_score: 89.0,
    confidence_score: 87.0,
    eligibility_assessment: "eligible",
    reasoning: "Strong alignment with programme's FinTech focus. PayFlow Africa's traction and team quality meet the eligibility bar comfortably.",
    application_recommendation: "strong_apply",
  },
  {
    programme_id: "e0000000-0000-0000-0000-000000000002",
    programme_name: "GovTech Sandbox Kenya",
    organizer: "Kenya ICT Authority",
    country: "Kenya",
    focus_area: ["GovTech", "FinTech"],
    duration_weeks: 12,
    funding_offered: 50000,
    status: "open",
    benefits: ["$50K grant", "Government contracts", "Regulatory sandbox"],
    fit_score: 76.0,
    confidence_score: 72.0,
    eligibility_assessment: "likely_eligible",
    reasoning: "Kenya-based startup with FinTech focus aligns well. The regulatory sandbox access could accelerate licensing.",
    application_recommendation: "apply",
  },
];

export const MOCK_VERIFICATION = {
  verification_score: 87.5,
  risk_level: "low",
  industry_classification: "FinTech",
  stage_classification: "seed",
  legitimacy_score: 85,
  confidence_level: 0.88,
  risk_factors: [
    "Competitive market with established players (M-Pesa, Flutterwave)",
    "Regulatory complexity across multiple African jurisdictions",
  ],
  strengths: [
    "Strong traction with 12,000 active users and $2M monthly volume",
    "Experienced team with relevant fintech background",
    "Clear revenue model with proven unit economics",
    "Strategic bank partnerships de-risk the business",
  ],
  recommendations: [
    "Accelerate Series A fundraising — metrics support a $3-5M round",
    "Expand to 2 additional African markets in next 12 months",
    "Strengthen compliance team ahead of regulatory expansion",
  ],
  ai_summary: "PayFlow Africa demonstrates strong fundamentals with proven traction and a clear market opportunity. The team has relevant fintech experience and the product addresses a real pain point. Series A readiness is high.",
};

export const MOCK_ANALYTICS = {
  monthly_growth: [
    { month: "2024-01-01", startups_added: 2 },
    { month: "2024-02-01", startups_added: 3 },
    { month: "2024-03-01", startups_added: 1 },
  ],
  top_startups: MOCK_STARTUPS.sort((a, b) => b.verification_score - a.verification_score).slice(0, 5),
  engagement_trend: [
    { week: "2024-01-01", engagements: 3 },
    { week: "2024-01-08", engagements: 5 },
    { week: "2024-01-15", engagements: 4 },
    { week: "2024-01-22", engagements: 7 },
  ],
};

// ─── New Mock Data for v2 Features ───────────────────────────────────────────

export const MOCK_BLUEPRINTS = [
  {
    id: "bp-001", name: "3-Month Growth Mentorship", description: "Structured 12-week mentorship with bi-weekly check-ins and 3 milestone checkpoints",
    relationship_type: "mentor_startup", duration_weeks: 12, required_checkins_per_month: 2,
    milestone_week_schedule: [4, 8, 12], health_alert_threshold: 60, escalation_threshold: 40,
    inactivity_alert_days: 7, auto_complete_on_end_date: true, usage_count: 8, avg_outcome_rating: 4.2,
    eligibility_rules: { startup_min_verification_score: 65, mentor_min_rating: 4.0 },
    auto_actions: { on_inactivity: "nudge", on_health_below_threshold: "escalate", on_completion: "capture_outcome" },
    is_active: true, created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "bp-002", name: "Accelerator Enrolment", description: "Standard programme enrolment with milestone tracking and outcome capture",
    relationship_type: "startup_programme", duration_weeks: 16, required_checkins_per_month: 4,
    milestone_week_schedule: [4, 8, 12, 16], health_alert_threshold: 55, escalation_threshold: 35,
    inactivity_alert_days: 5, auto_complete_on_end_date: true, usage_count: 5, avg_outcome_rating: 4.5,
    eligibility_rules: { startup_min_verification_score: 70 },
    auto_actions: { on_inactivity: "nudge", on_health_below_threshold: "escalate", on_completion: "capture_outcome" },
    is_active: true, created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "bp-003", name: "Seed Investment Track", description: "Investment relationship with quarterly review milestones",
    relationship_type: "startup_investor", duration_weeks: 24, required_checkins_per_month: 1,
    milestone_week_schedule: [8, 16, 24], health_alert_threshold: 50, escalation_threshold: 30,
    inactivity_alert_days: 14, auto_complete_on_end_date: false, usage_count: 3, avg_outcome_rating: 3.8,
    eligibility_rules: { startup_min_verification_score: 75 },
    auto_actions: { on_inactivity: "nudge", on_health_below_threshold: "escalate", on_completion: "capture_outcome" },
    is_active: true, created_at: "2024-03-01T00:00:00Z",
  },
];

export const MOCK_GOVERNANCE_RULES = [
  {
    id: "gr-001", name: "Mentor Capacity Cap", description: "A mentor cannot exceed their maximum startup capacity",
    rule_type: "capacity", scope: "platform",
    condition_json: { field: "mentor.current_startups", operator: ">=", value: "mentor.max_startups" },
    action_json: { type: "block", message: "Mentor has reached maximum startup capacity" },
    is_active: true, violation_count: 3, created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "gr-002", name: "Minimum Verification Score", description: "Startups must have a minimum verification score of 40",
    rule_type: "eligibility", scope: "platform",
    condition_json: { field: "startup.verification_score", operator: "<", value: "40" },
    action_json: { type: "warn", message: "Startup has a low verification score — proceed with caution" },
    is_active: true, violation_count: 7, created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "gr-003", name: "Critical Risk Block", description: "Startups with critical risk cannot be matched",
    rule_type: "eligibility", scope: "platform",
    condition_json: { field: "startup.risk_level", operator: "==", value: "critical" },
    action_json: { type: "block", message: "Startup is flagged as critical risk" },
    is_active: true, violation_count: 1, created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "gr-004", name: "Mentor Rating Minimum", description: "Only mentors with rating ≥ 3.5 can be matched via blueprints",
    rule_type: "quality", scope: "platform",
    condition_json: { field: "mentor.rating", operator: "<", value: "3.5" },
    action_json: { type: "warn", message: "Mentor rating below recommended threshold" },
    is_active: true, violation_count: 2, created_at: "2024-02-01T00:00:00Z",
  },
];

export const MOCK_COHORTS = [
  {
    id: "cohort-001", name: "West Africa FinTech Cohort 2024", programme_name: "Pan-African Accelerator",
    country: "Ghana", description: "Q1 2024 cohort focused on FinTech startups across West Africa",
    startup_ids: ["s-001", "s-002", "s-003"], mentor_ids: ["m-001", "m-002"],
    blueprint_id: "bp-001", blueprint_name: "3-Month Growth Mentorship",
    status: "active", startup_count: 3, mentor_count: 2, relationship_count: 3,
    approved_at: "2024-03-01T00:00:00Z", created_at: "2024-02-15T00:00:00Z",
    match_matrix: {
      startups: [
        { id: "s-001", name: "PayFlow Africa", industry: "FinTech", stage: "seed" },
        { id: "s-002", name: "AgriConnect", industry: "AgriTech", stage: "mvp" },
        { id: "s-003", name: "EduBridge", industry: "EdTech", stage: "seed" },
      ],
      mentors: [
        { id: "m-001", name: "Dr. Michael Chen", expertise: ["FinTech", "Strategy"] },
        { id: "m-002", name: "Amara Okonkwo", expertise: ["Product", "Growth"] },
      ],
      scores: {
        "s-001": { "m-001": { score: 92, reasoning: "Strong FinTech alignment" }, "m-002": { score: 74, reasoning: "Growth expertise relevant" } },
        "s-002": { "m-001": { score: 68, reasoning: "Limited agri domain knowledge" }, "m-002": { score: 85, reasoning: "Strong product fit" } },
        "s-003": { "m-001": { score: 72, reasoning: "Moderate alignment" }, "m-002": { score: 88, reasoning: "EdTech growth experience" } },
      },
      optimal_assignment: {
        "s-001": { mentor_id: "m-001", score: 92, reasoning: "Strong FinTech alignment" },
        "s-002": { mentor_id: "m-002", score: 85, reasoning: "Strong product fit" },
        "s-003": { mentor_id: "m-002", score: 88, reasoning: "EdTech growth experience" },
      },
      computed_at: "2024-02-28T12:00:00Z",
    },
  },
  {
    id: "cohort-002", name: "East Africa HealthTech Sprint", programme_name: "Health Innovation Hub",
    country: "Kenya", description: "6-week intensive for health technology startups",
    startup_ids: ["s-004", "s-005"], mentor_ids: ["m-003"],
    blueprint_id: "bp-002", blueprint_name: "Accelerator Enrolment",
    status: "draft", startup_count: 2, mentor_count: 1, relationship_count: 0,
    approved_at: null, created_at: "2024-04-01T00:00:00Z",
    match_matrix: {},
  },
];

export const MOCK_OUTCOMES = [
  {
    id: "out-001", relationship_id: "rel-001", startup_id: "s-001", startup_name: "PayFlow Africa",
    mentor_name: "Dr. Michael Chen", relationship_type: "mentor_startup",
    funding_raised_after: 250000, milestone_completion_rate: 0.83, mentor_nps: 9,
    programme_graduation: false, overall_rating: 5, success_classification: "high",
    key_wins: ["Secured seed round", "Launched in 3 new markets", "Team grew from 4 to 12"],
    key_challenges: ["Regulatory compliance in Ghana"],
    key_success_factors: ["Weekly structured check-ins", "Network introductions by mentor"],
    learning_points: ["Early fundraising guidance is critical", "Market-specific compliance needs specialist"],
    pattern_tags: ["high-growth", "funded", "market-expansion"],
    ai_summary: "This mentorship achieved exceptional outcomes. The mentor's FinTech network directly contributed to the seed round close and market expansion strategy.",
    captured_at: "2024-06-15T00:00:00Z",
  },
  {
    id: "out-002", relationship_id: "rel-002", startup_id: "s-002", startup_name: "AgriConnect",
    mentor_name: "Amara Okonkwo", relationship_type: "mentor_startup",
    funding_raised_after: 50000, milestone_completion_rate: 0.67, mentor_nps: 7,
    programme_graduation: false, overall_rating: 4, success_classification: "medium",
    key_wins: ["Product launched in 2 regions", "500+ farmer signups"],
    key_challenges: ["Customer acquisition cost too high", "Logistics complexity"],
    key_success_factors: ["Product iteration guidance", "User research methodology"],
    learning_points: ["B2B vs B2C model needs early clarity"],
    pattern_tags: ["product-led", "rural-markets"],
    ai_summary: "Good progress with product development but commercialisation challenges remain. The mentorship provided strong product guidance with some gaps in go-to-market expertise.",
    captured_at: "2024-07-01T00:00:00Z",
  },
];

export const MOCK_OUTCOME_INSIGHTS = {
  total_outcomes: 12, avg_rating: 4.1, high_success_rate: 58.3,
  top_industries: [
    { industry: "FinTech", count: 4, avg_rating: 4.5 },
    { industry: "HealthTech", count: 3, avg_rating: 4.0 },
    { industry: "EdTech", count: 3, avg_rating: 3.8 },
    { industry: "AgriTech", count: 2, avg_rating: 4.2 },
  ],
  ai_insights: {
    headline: "FinTech mentorships show 40% higher funding success rates than other sectors",
    key_insights: [
      "Mentorships with blueprint-defined milestones complete 65% more goals on time",
      "Startups with verification score above 70 have 2× higher programme graduation rates",
      "West Africa cohorts raised 3× more funding post-mentorship than East Africa in this period",
      "Relationships with weekly check-ins maintained 'good' or better health 87% of the time",
    ],
    patterns: ["High-frequency engagement correlates with funding success", "Geographic mentor proximity improves NPS scores"],
    recommendations: ["Prioritise blueprint-based relationships for all new cohorts", "Expand FinTech mentor pool by 40% for next quarter"],
  },
};

export const MOCK_LIFECYCLE_EVENTS = [
  { id: "le-001", relationship_id: "rel-001", event_type: "health_check", triggered_by: "scheduler", payload: { health_score: 72, engagement_health: "good" }, created_at: new Date(Date.now() - 3600000).toISOString() },
  { id: "le-002", relationship_id: "rel-002", event_type: "nudge_sent", triggered_by: "scheduler", payload: { days_inactive: 8, message: "No activity in 8 days" }, created_at: new Date(Date.now() - 7200000).toISOString() },
  { id: "le-003", relationship_id: "rel-003", event_type: "milestone_due", triggered_by: "scheduler", payload: { milestone_title: "Mid-Point Review", due_date: "2024-05-15" }, created_at: new Date(Date.now() - 86400000).toISOString() },
  { id: "le-004", relationship_id: "rel-001", event_type: "escalation", triggered_by: "scheduler", payload: { health_score: 38, message: "Health score below escalation threshold" }, created_at: new Date(Date.now() - 172800000).toISOString() },
  { id: "le-005", relationship_id: "rel-002", event_type: "log_added", triggered_by: "user", payload: { activity_type: "mentor_call" }, created_at: new Date(Date.now() - 259200000).toISOString() },
];

export const MOCK_LIFECYCLE_SUMMARY = {
  at_risk: [
    { id: "rel-004", relationship_type: "mentor_startup", health_score: 35, engagement_health: "poor", startup_name: "EduBridge" },
    { id: "rel-005", relationship_type: "startup_programme", health_score: 48, engagement_health: "fair", startup_name: "HealthFirst" },
  ],
  pending_milestones: [
    { id: "ms-001", title: "Mid-Point Review", due_date: "2024-05-20", startup_name: "PayFlow Africa", relationship_id: "rel-001" },
    { id: "ms-002", title: "Final Milestone", due_date: "2024-05-25", startup_name: "AgriConnect", relationship_id: "rel-002" },
  ],
  recent_events: MOCK_LIFECYCLE_EVENTS,
};

export const MOCK_GRAPH_DIAGNOSTICS = {
  orphans: {
    startups: [{ id: "s-007", name: "CloudPay", industry: "FinTech", country: "Nigeria", days_since_join: 14 }],
    mentors: [{ id: "m-005", name: "Fatima Al-Said", expertise: ["AI/ML", "Product"], availability: "available" }],
    total: 2,
  },
  overloaded: [],
  cluster_gaps: [
    { industry: "CleanTech", startup_count: 2, missing_entity_type: "mentor", recommendation: "Recruit CleanTech mentors — 2 startups lack mentorship coverage" },
  ],
  bridge_suggestions: [
    { from_entity: { type: "startup", id: "s-007", name: "CloudPay" }, to_entity: { type: "mentor", id: "m-005", name: "Fatima Al-Said" }, reason: "Strong FinTech alignment with AI/ML mentor expertise", potential_score: 88 },
    { from_entity: { type: "startup", id: "s-003", name: "EduBridge" }, to_entity: { type: "investor", id: "i-002", name: "AfricaGrowth Capital" }, reason: "EdTech focus aligns with investor thesis on education tech in East Africa", potential_score: 82 },
  ],
  governance_alerts: [
    { rule_name: "Mentor Capacity Cap", affected_count: 1, severity: "warning" },
  ],
};
